spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: BOOK-MS
          uri: lb://BOOK-MS
          predicates:
            - Path=/api/v1/books/**
        - id: ORDER-MS
          uri: lb://ORDER-MS
          predicates:
            - Path=/api/v1/orders/**
        - id: METRIC-ALERTS-MS
          uri: lb://METRIC-ALERTS-MS
          predicates:
            - Path=/api/v1/alerts/**
metrics:
  enabled: true
  cpu:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "cpu-metrics"
    interval: 5000
  ram:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "ram-metrics"
    interval: 5000

service:
  name: ${spring.application.name}
  instance: ${random.uuid}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  instance:
    prefer-ip-address: true
