spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: BOOK-MS
          uri: lb://BOOK-MS
          predicates:
            - Path=/api/v1/books/**
        - id: ORDER-MS
          uri: lb://ORDER-MS
          predicates:
            - Path=/api/v1/orders/**
