spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: BOOK-MS
          uri: lb://BOOK-MS
          predicates:
            - Path=/api/v1/books/**
        - id: ORDER-MS
          uri: lb://ORDER-MS
          predicates:
            - Path=/api/v1/orders/**
metrics:
  cpu:
    enabled: true
    kafka:
      acts: no_confirmation
      bootstrap-servers: localhost:9092
      topic: "cpu-metrics"
    application-name: ${spring.application.name}
    instance-name: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE
