spring:
  application:
    name: book-ms
  config:
    import: optional:configserver:http://localhost:8888/
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
server:
  port: 0
metrics:
  cpu:
    enabled: true
    kafka:
      acts: no_confirmation
      bootstrap-servers: localhost:9092
      topic: "cpu-metrics"
    application-name: ${spring.application.name}
    instance-name: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE