spring:
  application:
    name: ms2
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
