spring:
  application:
    name: system-metrics-analyzer-ms
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
metrics:
  enabled: true
  cpu:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "cpu-metrics"
    interval: 5000
  ram:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "ram-metrics"
    interval: 5000
service:
  name: ${spring.application.name}
  instance: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE
    pl.mzuchnik: DEBUG
