spring:
  application:
    name: metric-alerts-ms
  config:
    import: optional:configserver:http://localhost:8888/
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 0
