spring:
  application:
    name: order-ms
  config:
    import: optional:configserver:http://localhost:8888/
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
server:
  port: 0