spring:
  application:
    name: order-ms
  config:
    import: optional:configserver:http://localhost:8888/
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/arch-course}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/arch-course/protocol/openid-connect/certs}
      client:
        provider:
          keycloak-order-ms:
            issuer-uri: http://localhost:8090/realms/arch-course
        registration:
          keycloak-order-ms:
            client-id: arch-course-order-ms
            client-secret: gMozNFr16qTusb8dz7hmYPdkA3HgMtZN #<--- local
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: openid,order_roles,book_role
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
server:
  port: 0

metrics:
  enabled: true
  cpu:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "cpu-metrics"
    interval: 60000
  ram:
    kafka:
      bootstrap-servers: http://localhost:9092
      topic: "ram-metrics"
    interval: 60000

service:
  name: ${spring.application.name}
  instance: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE
    org.zalando.logbook: TRACE
logbook:
  predicate:
    include:
      - path: /api/**
        methods:
          - GET
          - POST
      - path: /actuator/**
    exclude:
      - path: /actuator/health
      - path: /api/admin/**
        methods:
          - POST
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 200
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000
  attribute-extractors:
    - type: JwtFirstMatchingClaimExtractor
      claim-names: [ "sub", "subject" ]
      claim-key: Principal
    - type: JwtAllMatchingClaimsExtractor
      claim-names: [ "sub", "iat" ]