spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
metrics:
  cpu:
    enabled: true
    kafka:
      acts: no_confirmation
      bootstrap-servers: localhost:9092
      topic: "cpu-metrics"
    application-name: ${spring.application.name}
    instance-name: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE