spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mzuchnik/course-architektit-config.git
          default-label: main
          refresh-rate: 30
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
server:
  port: 8888
metrics:
  cpu:
    enabled: true
    kafka:
      acts: no_confirmation
      bootstrap-servers: localhost:9092
      topic: "cpu-metrics"
    application-name: ${spring.application.name}
    instance-name: ${eureka.instance.instance-id}
logging:
  level:
    pl.mzuchnik.commonkafkacpumetrics: TRACE
