spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mzuchnik/course-architektit-config.git
          default-label: main
server:
  port: 8888
